version: "3"
services:
  app:
    build:
      context: .
    command: python main.py
    restart: on-failure
    env_file: .env

  nginx:
    image: nginx:1.17
    volumes:
      - ./.deploy/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    env_file: .env
    ports:
      - 80:80
    depends_on:
      - app
